const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const userSchema= new Schema({
    username:{
        type:String,
        required:true,
        unique:true,
        minlength:5
    },
    password:{
        type:String,
        required:true,
        minlength:8
    },
    name:{
        type:String,
        required:true
    },
    surname:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    PhoneNumber:{
        type:Number,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    AFM:{
        type:String,
        required:true
    },
    listed:{
        type:Boolean,
        required:true
    },
    rating:{
        type:String,
        required:true
    },
    number_of_ratings:{
        type:Number,
        required:true
    },
    country:{
        type:String,
        required:true
    }
},{
    timestamps:true,
    });
const User=mongoose.model('User',userSchema);
module.exports=User;